name = "perky-api"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_URL = "http://localhost:5173"

[[d1_databases]]
binding = "DB"
database_name = "perky-db"
database_id = "local"
migrations_dir = "../../migrations"

[[kv_namespaces]]
binding = "AUTH_KV"
id = "local"

[[r2_buckets]]
binding = "DOCUMENTS"
bucket_name = "perky-documents"
